update extras

diff --git a/extras b/extras
--- a/extras
+++ b/extras
@@ -15,19 +15,6 @@ test -f $HOME/.kube/config && test -f $HOME/.kube/azure/config && export KUBECON
 alias k=kubectl kx=kubectx kn=kubens
 alias kunset="kubectl config unset current-context; kubectl config unset current-context &>/dev/null"
 
-## Shell configuration
-test $SHELL = "/bin/bash" && test $(uname -s) = "Darwin" \
-&& brew_etc="$(brew --prefix)/etc" \
-&& [[ -r "${brew_etc}/profile.d/bash_completion.sh" ]] && source "${brew_etc}/profile.d/bash_completion.sh"
-
-test $SHELL = "/bin/bash" && source <(kubectl completion bash)
-test $SHELL = "/bin/bash" && complete -o default -F __start_kubectl k
-
-test $SHELL = "/bin/zsh" && source <(kubectl completion zsh)
-test $SHELL = "/bin/zsh" && autoload -Uz compinit && compinit
-
-test $SHELL = "/bin/zsh" && ZSH_THEME_TF_PROMPT_PREFIX="[terraform:" && RPROMPT=$(echo $(aws_prompt_info) $(tf_prompt_info))
-
 ## Python
 alias py=python3
 
@@ -50,16 +37,49 @@ alias tfv="terraform validate"
 alias tfiu="terraform init -upgrade"
 alias tfip="tfi && tfp"
 
-# ## AWS alias
-export AWS_PROFILE=$(aws configure list-profiles | grep "mfa" | head -1)
+## Pulumi alias
+alias p="pulumi"
+alias pp="pulumi preview"
+alias pu="pulumi up"
+alias puy="pulumi up -y"
+alias pd="pulumi down"
+alias ps="pulumi stack"
+alias psi="pulumi stack init"
+alias psl="pulumi stack ls"
+alias pss="pulumi stack select"
 
-for profile in $(aws configure list-profiles); do
-  if [ "$profile" != "mfa" ]; then
-  alias awsprofile-$profile="aws --profile $profile"
-  alias awsset-$profile="export AWS_PROFILE=$profile"
-  alias e1sprofile-$profile="e1s --profile=$profile"
-  fi
-done
+## AWS alias
+AWS_REGION="us-east-2"
+
+aws_mfa_profile=$(aws configure list-profiles | grep "mfa")
+test $aws_mfa_profile && AWS_PROFILE=$aws_mfa_profile || AWS_PROFILE=$(aws configure list-profiles | head -n 1)
+
+if [ $SHELL = "/bin/bash" ]; then
+  for profile in $(aws configure list-profiles); do
+    if [ "$profile" != "mfa" ]; then
+    alias awsprofile-$profile="AWS_PROFILE=$profile"
+    alias e1sprofile-$profile="e1s --profile=$profile"
+    fi
+  done
+
+  regions=("us-east-1" "us-east-2" "us-west-1" "eu-central-1")
+  for region in $regions; do
+    alias awsregion-$region="AWS_REGION=$region"
+  done
+fi
+
+## Shell configuration
+test $SHELL = "/bin/bash" && test $(uname -s) = "Darwin" \
+&& brew_etc="$(brew --prefix)/etc" \
+&& [[ -r "${brew_etc}/profile.d/bash_completion.sh" ]] && source "${brew_etc}/profile.d/bash_completion.sh"
+
+test $SHELL = "/bin/bash" && source <(kubectl completion bash)
+test $SHELL = "/bin/bash" && complete -o default -F __start_kubectl k
+
+test $SHELL = "/bin/zsh" && source <(kubectl completion zsh)
+test $SHELL = "/bin/zsh" && autoload -Uz compinit && compinit
+
+test $SHELL = "/bin/zsh" && RPROMPT=$(aws_prompt_info)
 
 ## OpenVPN
 alias ovpn-c="openvpn3 session-start --config ~/.client.ovpn"
@@ -81,51 +101,53 @@ function extractpublic() { openssl pkcs12 -in $1 -clcerts -nokeys -out "public.c
 function extractca() { openssl pkcs12 -in $1 -cacerts -nokeys -chain -out "ca.crt"; }
 
 ## AWS MFA
-function aws-mfa() {
-local SOURCE_PROFILE=$AWS_PROFILE
-local MFA_PROFILE="$AWS_PROFILE-mfa"
+if [ $SHELL = "/bin/bash" ]; then
+  function aws-mfa() {
+  local SOURCE_PROFILE=$AWS_PROFILE
+  local MFA_PROFILE="$AWS_PROFILE-mfa"
 
-local MFA_DEVICE_ARN=$(aws configure get mfa_device_arn --profile $SOURCE_PROFILE)
-if [ -z "$MFA_DEVICE_ARN" ]; then
-   echo "Error: MFA device ARN not found in the ~/.aws/credentials file for profile $SOURCE_PROFILE"
-   return 1
+  local MFA_DEVICE_ARN=$(aws configure get mfa_device_arn --profile $SOURCE_PROFILE)
+  if [ -z "$MFA_DEVICE_ARN" ]; then
+    echo "Error: MFA device ARN not found in the ~/.aws/credentials file for profile $SOURCE_PROFILE"
+    return 1
+  fi
+
+  echo "Enter your MFA token code:"
+  read MFA_CODE
+
+  local CREDENTIALS=$(aws sts get-session-token \
+    --serial-number "$MFA_DEVICE_ARN" \
+    --token-code "$MFA_CODE" \
+    --profile "$SOURCE_PROFILE" \
+    --output json 2>/dev/null)
+
+  if [ $? -ne 0 ]; then
+    echo "Error: Failed to obtain temporary credentials. Please check your MFA token code and try again."
+    return 1
+  fi
+
+  # Extract the credentials from the JSON response
+  local ACCESS_KEY=$(echo "$CREDENTIALS" | jq -r '.Credentials.AccessKeyId')
+  local SECRET_KEY=$(echo "$CREDENTIALS" | jq -r '.Credentials.SecretAccessKey')
+  local SESSION_TOKEN=$(echo "$CREDENTIALS" | jq -r '.Credentials.SessionToken')
+  local EXPIRATION=$(echo "$CREDENTIALS" | jq -r '.Credentials.Expiration')
+
+  # Check if the credentials are not empty
+  if [ -z "$ACCESS_KEY" ] || [ -z "$SECRET_KEY" ] || [ -z "$SESSION_TOKEN" ]; then
+    echo "Error: Failed to parse temporary credentials. Please try again."
+    return 1
+  fi
+
+  # Store the temporary credentials in the MFA profile
+  aws configure set aws_access_key_id "$ACCESS_KEY" --profile "$MFA_PROFILE"
+  aws configure set aws_secret_access_key "$SECRET_KEY" --profile "$MFA_PROFILE"
+  aws configure set aws_session_token "$SESSION_TOKEN" --profile "$MFA_PROFILE"
+
+  echo "Temporary credentials have been set for the '$MFA_PROFILE' profile. They will expire on $EXPIRATION."
+
+  # Export the AWS_PROFILE environment variable to use the MFA profile
+  AWS_PROFILE="$MFA_PROFILE"
+  echo "AWS_PROFILE environment variable set to '$MFA_PROFILE'."
+
+  }
 fi
-
-echo "Enter your MFA token code:"
-read MFA_CODE
-
-local CREDENTIALS=$(aws sts get-session-token \
-   --serial-number "$MFA_DEVICE_ARN" \
-   --token-code "$MFA_CODE" \
-   --profile "$SOURCE_PROFILE" \
-   --output json 2>/dev/null)
-
-if [ $? -ne 0 ]; then
-   echo "Error: Failed to obtain temporary credentials. Please check your MFA token code and try again."
-   return 1
-fi
-
-# Extract the credentials from the JSON response
-local ACCESS_KEY=$(echo "$CREDENTIALS" | jq -r '.Credentials.AccessKeyId')
-local SECRET_KEY=$(echo "$CREDENTIALS" | jq -r '.Credentials.SecretAccessKey')
-local SESSION_TOKEN=$(echo "$CREDENTIALS" | jq -r '.Credentials.SessionToken')
-local EXPIRATION=$(echo "$CREDENTIALS" | jq -r '.Credentials.Expiration')
-
-# Check if the credentials are not empty
-if [ -z "$ACCESS_KEY" ] || [ -z "$SECRET_KEY" ] || [ -z "$SESSION_TOKEN" ]; then
-   echo "Error: Failed to parse temporary credentials. Please try again."
-   return 1
-fi
-
-# Store the temporary credentials in the MFA profile
-aws configure set aws_access_key_id "$ACCESS_KEY" --profile "$MFA_PROFILE"
-aws configure set aws_secret_access_key "$SECRET_KEY" --profile "$MFA_PROFILE"
-aws configure set aws_session_token "$SESSION_TOKEN" --profile "$MFA_PROFILE"
-
-echo "Temporary credentials have been set for the '$MFA_PROFILE' profile. They will expire on $EXPIRATION."
-
-# Export the AWS_PROFILE environment variable to use the MFA profile
-export AWS_PROFILE="$MFA_PROFILE"
-echo "AWS_PROFILE environment variable set to '$MFA_PROFILE'."
-
-}
