update extras

diff --git a/extras b/extras
--- a/extras
+++ b/extras
@@ -49,23 +49,36 @@ alias psl="pulumi stack ls"
 alias pss="pulumi stack select"
 
 ## AWS alias
-AWS_REGION="us-east-2"
-
 aws_mfa_profile=$(aws configure list-profiles | grep "mfa")
 test $aws_mfa_profile && AWS_PROFILE=$aws_mfa_profile || AWS_PROFILE=$(aws configure list-profiles | head -n 1)
 
-if [ $SHELL = "/bin/bash" ]; then
-  for profile in $(aws configure list-profiles); do
-    if [ "$profile" != "mfa" ]; then
-    alias awsprofile-$profile="AWS_PROFILE=$profile"
-    alias e1sprofile-$profile="e1s --profile=$profile"
-    fi
-  done
+test $SHELL = "/bin/zsh" && AWS_PROFILE_STATE_ENABLED=true
 
-  regions=("us-east-1" "us-east-2" "us-west-1" "eu-central-1")
-  for region in $regions; do
-    alias awsregion-$region="AWS_REGION=$region"
-  done
+if [ $SHELL = "/bin/zsh" ]; then
+    # Functions to redefine export and update the prompt
+    function my_export() {
+        builtin export "$@"
+        if [[ "$1" == "AWS_PROFILE"* ]] || [[ "$1" == "AWS_REGION"* ]]; then
+            update_aws_prompt
+        fi
+    }
+
+    alias export='my_export'
+
+    # Function to update the RPROMPT
+    function update_aws_prompt() {
+        zmodload zsh/parameter
+        RPROMPT='$(aws_prompt_info)'
+        zle && zle reset-prompt
+    }
+
+    # Function precmd to update RPROMPT
+    function precmd() {
+        update_aws_prompt
+    }
+
+    # RPROMPT configuration
+    RPROMPT='$(aws_prompt_info)'
 fi
 
 ## Shell configuration
@@ -88,9 +101,9 @@ alias ovpn-d="openvpn3 session-manage --config ~/.client.ovpn --disconnect"
 ### Functions
 findhere() {
   if [[ "$SHELL" == "/bin/bash" ]]; then
-    find . -name "*$1*"
+      find . -name "*$1*"
   elif [[ "$SHELL" == "/bin/zsh" ]]; then
-    echo **"$1"**
+      echo **"$1"**
   fi
 }
 function opensslcert() { openssl s_client -showcerts -connect $1:443; }
@@ -102,52 +115,52 @@ function extractca() { openssl pkcs12 -in $1 -cacerts -nokeys -chain -out "ca.cr
 
 ## AWS MFA
 if [ $SHELL = "/bin/bash" ]; then
-  function aws-mfa() {
-  local SOURCE_PROFILE=$AWS_PROFILE
-  local MFA_PROFILE="$AWS_PROFILE-mfa"
+    function aws-mfa() {
+    local SOURCE_PROFILE=$AWS_PROFILE
+    local MFA_PROFILE="$AWS_PROFILE-mfa"
 
-  local MFA_DEVICE_ARN=$(aws configure get mfa_device_arn --profile $SOURCE_PROFILE)
-  if [ -z "$MFA_DEVICE_ARN" ]; then
-    echo "Error: MFA device ARN not found in the ~/.aws/credentials file for profile $SOURCE_PROFILE"
-    return 1
-  fi
+    local MFA_DEVICE_ARN=$(aws configure get mfa_device_arn --profile $SOURCE_PROFILE)
+    if [ -z "$MFA_DEVICE_ARN" ]; then
+      echo "Error: MFA device ARN not found in the ~/.aws/credentials file for profile $SOURCE_PROFILE"
+      return 1
+    fi
 
-  echo "Enter your MFA token code:"
-  read MFA_CODE
+    echo "Enter your MFA token code:"
+    read MFA_CODE
 
-  local CREDENTIALS=$(aws sts get-session-token \
-    --serial-number "$MFA_DEVICE_ARN" \
-    --token-code "$MFA_CODE" \
-    --profile "$SOURCE_PROFILE" \
-    --output json 2>/dev/null)
+    local CREDENTIALS=$(aws sts get-session-token \
+      --serial-number "$MFA_DEVICE_ARN" \
+      --token-code "$MFA_CODE" \
+      --profile "$SOURCE_PROFILE" \
+      --output json 2>/dev/null)
 
-  if [ $? -ne 0 ]; then
-    echo "Error: Failed to obtain temporary credentials. Please check your MFA token code and try again."
-    return 1
-  fi
+    if [ $? -ne 0 ]; then
+      echo "Error: Failed to obtain temporary credentials. Please check your MFA token code and try again."
+      return 1
+    fi
 
-  # Extract the credentials from the JSON response
-  local ACCESS_KEY=$(echo "$CREDENTIALS" | jq -r '.Credentials.AccessKeyId')
-  local SECRET_KEY=$(echo "$CREDENTIALS" | jq -r '.Credentials.SecretAccessKey')
-  local SESSION_TOKEN=$(echo "$CREDENTIALS" | jq -r '.Credentials.SessionToken')
-  local EXPIRATION=$(echo "$CREDENTIALS" | jq -r '.Credentials.Expiration')
+    # Extract the credentials from the JSON response
+    local ACCESS_KEY=$(echo "$CREDENTIALS" | jq -r '.Credentials.AccessKeyId')
+    local SECRET_KEY=$(echo "$CREDENTIALS" | jq -r '.Credentials.SecretAccessKey')
+    local SESSION_TOKEN=$(echo "$CREDENTIALS" | jq -r '.Credentials.SessionToken')
+    local EXPIRATION=$(echo "$CREDENTIALS" | jq -r '.Credentials.Expiration')
 
-  # Check if the credentials are not empty
-  if [ -z "$ACCESS_KEY" ] || [ -z "$SECRET_KEY" ] || [ -z "$SESSION_TOKEN" ]; then
-    echo "Error: Failed to parse temporary credentials. Please try again."
-    return 1
-  fi
+    # Check if the credentials are not empty
+    if [ -z "$ACCESS_KEY" ] || [ -z "$SECRET_KEY" ] || [ -z "$SESSION_TOKEN" ]; then
+      echo "Error: Failed to parse temporary credentials. Please try again."
+      return 1
+    fi
 
-  # Store the temporary credentials in the MFA profile
-  aws configure set aws_access_key_id "$ACCESS_KEY" --profile "$MFA_PROFILE"
-  aws configure set aws_secret_access_key "$SECRET_KEY" --profile "$MFA_PROFILE"
-  aws configure set aws_session_token "$SESSION_TOKEN" --profile "$MFA_PROFILE"
+    # Store the temporary credentials in the MFA profile
+    aws configure set aws_access_key_id "$ACCESS_KEY" --profile "$MFA_PROFILE"
+    aws configure set aws_secret_access_key "$SECRET_KEY" --profile "$MFA_PROFILE"
+    aws configure set aws_session_token "$SESSION_TOKEN" --profile "$MFA_PROFILE"
 
-  echo "Temporary credentials have been set for the '$MFA_PROFILE' profile. They will expire on $EXPIRATION."
+    echo "Temporary credentials have been set for the '$MFA_PROFILE' profile. They will expire on $EXPIRATION."
 
-  # Export the AWS_PROFILE environment variable to use the MFA profile
-  AWS_PROFILE="$MFA_PROFILE"
-  echo "AWS_PROFILE environment variable set to '$MFA_PROFILE'."
+    # Export the AWS_PROFILE environment variable to use the MFA profile
+    AWS_PROFILE="$MFA_PROFILE"
+    echo "AWS_PROFILE environment variable set to '$MFA_PROFILE'."
 
-  }
+    }
 fi
